templates/account/email/adminnotification.html, templates/admin/userimport.html
https://jira4.prod.bloomberg.com/browse/RDISCROWD-1250?filter=-1
=> Change Note: to also asked for metadata

static/src/components/builder/components/ComponentRender.vue, static/src/components/builder/components/Header.vue, static/src/components/builder/components/PreviewCommons.vue, static/src/components/builder/components/Questions.vue, static/src/components/builder/components/TabSubHeader.vue, static/src/components/builder/components/Table/SlotTemplate.html, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/components/Table/TableTemplate.html, static/src/components/builder/components/helpers/alertBannerTemplate.html, static/src/components/builder/components/helpers/buttonRowTemplate.html, static/src/components/builder/components/helpers/cancelButtonTemplate.html, static/src/components/builder/components/helpers/submitButtonTemplate.html, static/src/components/builder/components/helpers/submitLastButtonTemplate.html, static/src/components/builder/components/helpers/taskPresenterTemplate.html, static/src/components/builder/components/helpers/timerTemplate.html, static/src/components/builder/components/helpers/userProgressTemplate.html, static/src/components/builder/router.js, static/src/components/builder/store/index.js, static/src/components/builder/store/modules/checkboxInput.js, static/src/components/builder/store/modules/table.js, static/src/components/builder/store/modules/textInput.js, static/src/components/builder/store/types.js, static/src/components/builder/utils.js
=> Component Helpers

templates/_formhelpers.html, templates/account/public_profile.html
https://jira4.prod.bloomberg.com/browse/RDISCROWD-1407
=> RDISCROWD-1407 Allow form fields to be disabled.

templates/projects/delete.html
https://jira4.prod.bloomberg.com/browse/RDISCROWD-984
=> RDISCROWD-984 Add a confirmation dialog when deleting a project.

templates/projects/delete.html
Brought this in sync with the projects/base.html.
=> Fix margin at top of project delete page.

static/src/.eslintrc.js, static/src/components/builder/components/CheckboxInput/CheckboxCreator.vue, static/src/components/builder/components/CheckboxInput/CheckboxInputForm.vue, static/src/components/builder/components/Header.vue, static/src/components/builder/components/PreviewCommons.vue, static/src/components/builder/components/TabSubHeader.vue, static/src/components/builder/components/Table/StaticData.vue, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/components/TextInput/TextInputForm.vue, static/src/components/builder/store/__mocks__/index.js, static/src/components/builder/store/__mocks__/modules/checkboxInput.js, static/src/components/builder/store/__mocks__/modules/textInput.js, static/src/components/builder/store/index.js, static/src/components/builder/store/modules/checkboxInput.js, static/src/components/builder/store/modules/table.js, static/src/components/builder/store/modules/textInput.js, static/src/components/builder/store/types.js, static/src/components/builder/utils.js, static/src/package.json, static/src/test/components/CheckboxCreator.spec.js, static/src/test/components/CheckboxInputForm.spec.js, static/src/test/components/TextInputForm.spec.js, static/src/test/store/checkboxInput.spec.js, static/src/test/utils.spec.js
- Fix state mutations directly
- Test added for all components related to checkbox
=> Fix mutatating state direclty and added test for checkboxInput

templates/projects/presenters/entity-tagging.html, templates/projects/presenters/pointshoot-base.html
names have to be changed in several places
=> fix template names

static/src/components/fieldsconfig/categorical_field_config.vue, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/tasks_browse.html
Check for empty labels before adding them
=> check empty labels

static/src/components/performancestats/confusion_matrix.vue, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/tasks_browse.html
Add a link to the definition of F-beta
=> explanation of b

.gitignore, static/src/components/performancestats/index.vue, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/tasks_browse.html
This way everybody with access to stats will be able to see them, even if they are not owners
=> add all=1 to stat queries

static/src/components/fieldsconfig/categorical_field_config.vue, static/src/test/components/fieldsconfig/categorical_field_config.spec.js, static/src/test/components/performancestats/index.spec.js, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/tasks_browse.html, templates/projects/wizard.html
Adding an option to have boolean answer fields
=> add true/false fields

templates/projects/task_presenter_editor.html
- Fixed spacing of github and project sync details.
- Updated style for panels.
- Added collapsible control.
Ref https://github.com/bloomberg/pybossa/pull/281
=> RDISCROWD-1694 UI updates for Github and project sync details

static/src/components/userprofile/recently_completed_tasks.vue, static/src/userprofile.js, static/src/webpack.config.js, templates/account/profile.html, templates/account/profile.webpack.ejs, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/tasks_browse.html, templates/projects/wizard.html
*Issue number of the reported bug or feature request: #1595*
Created a Vue component on the account profile page that will show the number of tasks the user has completed that day.
=> crowd-1595 recent tasks

.travis.yml
*Issue number of the reported bug or feature request: n/a*
Adding a travis.yml file
None
We need the file before travis can be enabled.
=> travis.yml for node

static/src/components/builder/components/ComponentRender/ComponentRender.vue, static/src/components/builder/components/Header.vue, static/src/components/builder/components/Questions.vue, static/src/components/builder/components/RadioInput/RadioInputForm.vue, static/src/components/builder/components/TabSubHeader.vue, static/src/components/builder/components/Table/ComponentColumns.vue, static/src/components/builder/components/Table/StaticData.vue, static/src/components/builder/components/Table/TableCreator.vue, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/store/__mocks__/modules/table.js, static/src/components/builder/store/modules/checkboxInput.js, static/src/components/builder/store/modules/radioInput.js, static/src/components/builder/store/modules/table.js, static/src/components/builder/store/modules/textInput.js, static/src/components/builder/store/modules/textTagging.js, static/src/components/builder/store/types.js, static/src/components/builder/utils.js, static/src/test/store/radioInput.spec.js, static/src/test/store/table.spec.js, static/src/test/utils/getters.js
*Issue number of the reported bug or feature request: no issue*
Adding field level validation for table builder and radio group builder in a manner consistent with the text tagging builder.
Also cleaned up the object method syntax to use the ES6 method syntax consistently.
Manual testing
=> Component builder validation

static/src/components/builder/components/TextTagging/TextTaggingForm.vue, static/src/components/builder/store/modules/textTagging.js
*Issue number of the reported bug or feature request: #RDISCROWD-1554*
Use HTML color picker for color field.
Move tooltip text to label so people will see it.
Manual testing
=> Color picker.

templates/projects/new.html
=> Remove message form template

static/src/components/builder/components/TextTagging/TextTaggingForm.vue, static/src/components/builder/store/modules/textTagging.js
*Issue number of the reported bug or feature request: #RDISCROWD-1554*
Remove unneeded html and css classes.
Improve wording of label tips.
Manual testing.
=> Clean up HTML.

static/src/components/builder/components/CheckboxInput/CheckboxInputForm.vue, static/src/components/builder/components/RadioInput/RadioInputForm.vue, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/components/TextTagging/TextTaggingForm.vue, static/src/components/fieldsconfig/index.vue
*Issue number of the reported bug or feature request: no issue*
Added label tips with explanatory text for Table and Radio Group builder.
Manual testing.
=> Label tips for component builder

static/src/components/builder/components/CheckboxInput/CheckboxInputForm.vue, static/src/components/builder/components/RadioInput/RadioInputForm.vue, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/components/TextTagging/TextTaggingForm.vue
*Issue number of the reported bug or feature request: #RDISCROWD-1554*
Use scoped styles in Vue components to prevent interference across components.
Manual
=> Use scoped styles.

static/src/components/builder/components/CheckboxInput/CheckboxInputForm.vue, static/src/components/builder/components/RadioInput/RadioInputForm.vue, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/components/TextTagging/TextTaggingForm.vue, static/src/test/store/textTagging.spec.js
*Issue number of the reported bug or feature request: #RDISCROWD-1554*
Fixes bugs where wrong control (or no control) is selected on label click.
Add unit tests for textTagging component.
Manual
=> Clean up UI. Add tests.

templates/_navbar.html, templates/projects/_helpers.html, templates/projects/base.html, templates/projects/publish.html, templates/projects/update.html
=> initial commit

templates/projects/presenters/relevancy.html, templates/projects/snippets/relevancy.html
- Added new template for Rating Topic Relevancy.
=> RDISCROWD-1904 Added "Rating Topic Relevancy" Template

templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs
*Issue number of the reported bug or feature request: #RDISCROWD-1983*
Show %Complete in task browse table for vendor co-owners.
Manual
=> Restore % complete field in task browse for vendors

templates/projects/update.html
*Issue number of the reported bug or feature request: #RDISCROWD-1872*
Added fields for annotation attributes to the project update form.
Manual
=> Add annotation fields to project.

templates/annotation_guidelines_button.html, templates/projects/presenter.html, templates/projects/task_presenter_editor.html, templates/projects/task_presenter_options.html
*Issue number of the reported bug or feature request: RDISCROWD-1976*
Include guidelines in task presenter, and a button to preview it, add update button in the new UI
=> Rdiscrowd 1976

templates/annotation_guidelines_button.html, templates/projects/task_presenter_editor.html
1. Expand and collapse
2. When clicking Test it button in the project, the guidelines must behave the same way, as when clicking contributing button.
3. Show the instructions by default
=> Fixes to be done:

templates/annotation_guidelines_button.html, templates/projects/presenter.html, templates/projects/task_presenter_editor.html
Hide instructions if there are no guidelines
=> Hide instruction button if project has never save a task_guidelines

static/sass/_pybossa.scss, static/sass/custom/dropdown.scss, static/sass/custom/switch_button.scss, static/src/components/fieldsconfig/categorical_field_config.vue, static/src/components/fieldsconfig/consensus_config.vue, static/src/components/fieldsconfig/field_config_base.vue, static/src/components/fieldsconfig/index.vue, static/src/components/setting/index.vue, static/src/components/setting/ownership_setting.vue, static/src/components/setting/quiz_setting.vue, static/src/components/setting/task_setting.vue, static/src/setting.js, static/src/test/components/fieldsconfig/consensus_config.spec.js, static/src/test/components/fieldsconfig/field_config_base.spec.js, static/src/test/components/fieldsconfig/index.spec.js, static/src/test/components/setting/index.spec.js, static/src/test/components/setting/ownship_setting.spec.js, static/src/test/components/setting/quiz_setting.spec.js, static/src/test/components/setting/task_setting.spec.js, static/src/webpack.config.js, templates/projects/answerfieldsconfig.webpack.ejs, templates/projects/summary.html, templates/projects/summary.webpack.ejs
Jira Issue
https://jira4.prod.bloomberg.com/browse/RDISCROWD-1575
Describe your changes
created a summary page to show necessary configurations current project has, with redirect links to original configuration pages for editing purpose.
=> Project summary

static/src/components/setting/index.vue, static/src/components/setting/task_setting.vue, static/src/test/components/setting/index.spec.js, static/src/test/components/setting/task_setting.spec.js, templates/projects/task_n_answers.html
This is to fix following issues
* display fields based on data access level configured.
* get/set field values works from wizard settings.
* add gold task probability to summary page.
* report error messages as per scope instead of generic errors.
* make config parameter labels under summary similar to the ones under project/task settings.
Tested local server with/without data access configured. Project/task configurations get/set from regular proj/task settings link also present under wizard settings option and vice versa. 
May need another PR to apply strong validation checks on form controls.
=> update summary pages

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js
honor data access as json string
=> jsonify data access

templates/projects/task_presenter_editor.html
=> prevent the page from jumping to element

static/src/components/setting/quiz_setting.vue, static/src/package.json, static/src/test/components/setting/quiz_result_table.spec.js, static/src/test/components/setting/quiz_setting.spec.js
=> Test Quiz Mode in summary page

templates/projects/presenter.html, templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs
=> Read only mode

static/sass/_pybossa.scss, static/sass/custom/navbar.scss, templates/_navbar.html
- Added platform indicator label under Gigwork logo.
- Added config option DISPLAY_PLATFORM_IDENTIFIER to show or hide the platform under the logo.
=> RDISCROWD-1151 Platform indicator label

static/sass/pybossa/_card.scss, templates/admin/index.html, templates/projects/_helpers.html, templates/projects/export.html, templates/projects/settings.html, templates/projects/task_settings.html, templates/projects/tasks.html
- Resizes tile thumbnails to display more per row on page.
- Responsive styling of thumbnail tiles.
**Pages Changed**
- Project Settings `/project/helloworld/settings`
- Tasks `/project/helloworld/tasks/`
- Task Settings `/project/helloworld/tasks/settings`
- Tasks Export `/project/helloworld/tasks/export`
- Admin `/admin`
- Media sizes styled:
- 0px-767px (tiny)
- 768px-991px (small)
- 992px-1200px (medium)
- 1200px+ (large)
The following screenshots may be compared to the [original](https://qa.gigwork.net/project/helloworld/settings) application.
=> RDISCROWD-2453 Resize settings thumbnail tiles and responsive styling

templates/projects/_helpers.html, templates/projects/clone_project.html
=> Add clone form html

templates/projects/project.html
*Issue number of the reported bug or feature request: #<2441>*
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2441
hide `total number of tasks remaining` from non-admin users.
=> Recalculate numbers on project info page

static/sass/custom/project.scss, templates/projects/new.html, templates/projects/update.html
- Added form field validation css to project new/update pages.
- Added password requirements label.
- Sorted products/subproducts drop-down.
=> RDISCROWD-2234 Project form field validation and styling

templates/projects/project.html
*Issue number of the reported bug or feature request: #<2441>*
=> 2441 - add new field on project info page

templates/projects/project.html
*Issue number of the reported bug or feature request: #<2441>*
=> 2441 - change text display

templates/projects/_helpers.html, templates/projects/base.html
- Added chat integration with Slack and Chatlio.
For a specific list of projects by `short_name` or `all`.
```
CHAT_ENABLE = ['all']
CHAT_URL = 'https://gigwork-dev.slack.com'
```
```
CHAT_ENABLE = ['project1', 'project2']
CHAT_URL = 'https://gigwork-dev.slack.com'
```
Related https://github.com/bloomberg/pybossa/pull/400
=> RDISCROWD-893 Chat integration

templates/projects/_helpers.html
=> Fix test, removing owner

static/src/package.json, templates/projects/publish.html
=> Remove publish flag

templates/projects/task_presenter_editor.html
*Issue number of the reported bug or feature request: RDISCROWD-2527*
Add a github sync panel for annotation guidelines to show details about the last github push that triggered an update to guidelines
Manual
=> Add github sync panel for annotation guidelines

templates/projects/project_report.html
=> project report date range template

static/js/tasks_browse.js
Sanitize the answers when they're displayed in task browser.
Manual.
=> crowd-2686 sanitize answers

templates/projects/task_presenter_editor.html
*Issue number of the reported bug or feature request: #RDISCROWD-2528*
Bug fix for displaying last task presenter push details.
Add support for displaying an error message in the push details.
Manual
=> Show bbgithub error, bug fix

templates/projects/task_presenter_editor.html
*Issue number of the reported bug or feature request: #2528-rdiscrowd
Bug fix in template
Manual
=> 2528 rdiscrowd

templates/projects/importers/localCSV.html
Move 'Cancel' button on task import page.
Manual
=> crowd-2035

templates/projects/task_presenter_editor.html
Change the `saveTask` override to return an object rather than `undefined`.
Manual
=> crowd-1889 task presenter preview fix

static/sass/custom/switch_button.scss, static/src/components/setting/quiz_result_table.vue, static/src/components/setting/quiz_setting.vue
- Updated hint text for quiz mode toggle button.
- Removed labels next to checkboxes in quiz mode user table.
=> RDISCROWD-2703 Quiz Mode Label Changes

static/src/components/builder/components/Table/tableTemplate.html, static/src/components/builder/utils.js
=> Don't include column-id prop if is not defined on snipet

static/src/components/fieldsconfig/index.vue, templates/account/profile.html, templates/admin/new_announcement.html, templates/projects/_helpers.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/summary.html, templates/projects/tasks_browse.html, templates/projects/wizard.html
=> show own performance stats to all

static/src/components/builder/store/modules/textInput.js
=> Clear validations after type changed

templates/projects/presenter.html
=> save-answ-locally

static/src/components/builder/store/modules/textInput.js
=> remove required

static/js/flashmessages.js
=> Update pybossaNotify to enable not removing previous notification

templates/projects/task_presenter_editor.html
- Updated icon for collapse/expand.
=> RDISCROWD-2747 Updated icon for collapse/expand.

static/src/components/fieldsconfig/categorical_nested_field_config.vue, static/src/components/fieldsconfig/index.vue, static/src/components/fieldsconfig/labelTypes.js, templates/account/profile.html, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/summary.html, templates/projects/tasks_browse.html, templates/projects/wizard.html
=> answer field config for nested consensus

templates/account/update.html, templates/projects/export.html, templates/projects/tasks.html
*Issue number of the reported bug or feature request: RDISCROWD-2962 *
I hid the references to CKAN in all the UI files that were showing them.
I checked to make sure the change was reflected in a few projects and tried saving minor changes.
**Related PR**
https://github.com/bloomberg/pybossa/pull/472
=> RDISCROWD-2962 Remove CKAN References

static/sass/custom/project.scss, templates/projects/task_notification.html
- Always show the webhook url textbox in task notifications.
- Resolves issue when clicking save.
- Refactor js.
=> RDISCROWD-3114 Show Webhook URL Textbox in Task Notifications

static/sass/custom/project.scss, templates/projects/task_notification.html
- Set threshold notification textbox to be of type `number`.
=> RDISCROWD-3114 Notification threshold number

templates/projects/project.html
- Added number of tasks in progress to the project summary page.
Re: https://github.com/bloomberg/pybossa/pull/477
=> RDISCROWD-3112 Number of locked tasks for tasks in progress

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js, templates/projects/new.html, templates/projects/update.html
- Added new input/output data classification drop-down controls to settings page.
=> input output data classification

templates/projects/project.html
=> update data classification label

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js
=> assign users under priv

templates/_footer.html, templates/home/index.html
https://jira.prod.bloomberg.com/browse/RDISCROWD-3172
Follow up changes to integrate feedback from users.
Tested to make UI looked as expected.
Screen shots of changes:
Screenshot 1
Screenshot 2
Screenshot 3
Screenshot 4
=> move pybossa reference to footer

templates/projects/transferownership.html
Corrected typo on ownership transfer page
Loaded locally to check that the spelling is now correct
Before: 
After:
=> trasfer -> transfer in transferownership.html

templates/projects/new.html, templates/projects/update.html
*Issue number of the reported bug or feature request: #<3237>*
=> RDISCROWD-3237 Make 'opt into AMP' checkbox stateful on page reload

static/src/test/components/performancestats/index.spec.js, templates/projects/tasks_browse.webpack.ejs
*Issue number of the reported bug or feature request: #<1966>*
=> RDISCROWD-1966 Description of table does not match what is displayed

static/src/components/builder/store/modules/multiselectInput.js, static/src/components/builder/utils.js, static/src/test/store/multiselectInput.spec.js, static/src/test/utils.spec.js
*Issue number of the reported bug or feature request:*
Bug fix for https://jira.prod.bloomberg.com/browse/RDISCROWD-3403
Empty strings in the initial value field were causing a blank blue line to appear if no initial value was provided.
All tests are passing.
=> fix blue line bug

templates/projects/presenters/annex.html, templates/projects/presenters/basic.html, templates/projects/presenters/entity-tagging.html, templates/projects/presenters/helper-components.html, templates/projects/presenters/pointshoot-base.html, templates/projects/presenters/relevancy.html
Issue number of the reported bug or feature request: RDISCROWD-1692: Update template descriptions on template tiles
Please see ticket for screen shots of updates.
=> RDISCROWD-1692: Update template descriptions on template tiles

static/src/components/common/gig_spinner.vue, static/src/components/setting/index.vue, static/src/components/setting/ownership_setting.vue, static/src/components/setting/quiz_setting.vue, static/src/components/setting/task_setting.vue, static/src/components/userprofile/recently_completed_tasks.vue, static/src/components/wizard/step.vue, static/src/package.json, static/src/test/components/setting/task_setting.spec.js
- Task **Notification Threshold** and **Task Notification Webhook URL** to project summary Vue component.
- Added progress spinner to tab dialogs.
=> RDISCROWD-2948 Task Notification link added to Task tab

templates/projects/task_settings.html, templates/projects/tasks.html, templates/projects/tasks/delete.html
=> Rdiscrowd 2324

static/src/components/setting/ownership_setting.vue
=> added line warap and increased the row height

static/src/components/setting/ownership_setting.vue
=> Rdiscrowd 4060 sub

templates/admin/index.html
=> RDISCROWD-1667: Added create user tile on admin page

static/sass/custom/project.scss, templates/_formhelpers.html, templates/projects/update.html
- Fixed tooltips not displaying when hovering on checkboxes and label.
- Corrected double-label HTML structure.
=> Fix for checkbox tooltips.

static/sass/custom/project.scss, templates/_formhelpers.html, templates/projects/update.html
- kwargs null check fix (for unit tests).
Re: https://github.com/bloomberg/pybossa/pull/603
=> Checkbox tooltip fix

templates/projects/tasks_browse.webpack.ejs
- Copied changes for task-browse.webpack.ejs
Re: https://github.com/bloomberg/pybossa/pull/604
=> Copied changes for task-browse.webpack.ejs

static/sass/pybossa/_card.scss, templates/projects/_helpers.html, templates/projects/snippets/options.html, templates/projects/task_presenter_options.html
- Fixed tiles to be responsive to left-nav.
- Fixed alignment on task import tile.
- Fixed left-nav on task presenter options.
=> Resize project tiles

static/sass/custom/project.scss, static/sass/pybossa/_card.scss, templates/projects/settings.html, templates/projects/task_settings.html
- Adjusted project tiles responsiveness.
=> Project tile font

templates/projects/task_scheduler.html
*Issue number of the reported bug or feature request: #<4458>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4458
=> 4458 configurable columns for task queues

templates/projects/tasks_browse.webpack.ejs
*Issue number of the reported bug or feature request: #<4381>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4381
=> RDISCROWD-4381 Task Queue patch: add ejs file change

templates/projects/presenter.html, templates/projects/tasks_browse.webpack.ejs
*Issue number of the reported bug or feature request: #<4416>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-4416
=> RDISCROWD-4416 lock task from task list

templates/projects/tasks_browse.webpack.ejs
https://jira.prod.bloomberg.com/browse/RDISCROWD-4386
**Describe your changes** 
=> RDISCROWD-4386 - auto refresh for worker view

templates/projects/tasks_browse.webpack.ejs
=> change refresh interval to 60s

templates/projects/tasks_browse.webpack.ejs
https://jira.prod.bloomberg.com/browse/RDISCROWD-4644
=> RDISCROWD-4644 add coowner options

templates/projects/_helpers.html, templates/projects/tasks_browse.webpack.ejs
- Allow admin/subadmin/coowner from tasklist view to submit tasks (not read-only mode).
Re: https://github.com/bloomberg/pybossa/pull/642
=> RDISCROWD-4747 Allow submitting tasks by admin/sub/owner in task list view

templates/projects/_helpers.html, templates/projects/tasks_browse.webpack.ejs
- RDISCROWD-4747 Hide gold indicator in tasklist view
=> RDISCROWD-4747 Hide gold indicator in tasklist view

static/src/components/task_browse/assign_worker.vue
=> RDISCROWD-4593-ui-fix add missing async save logic

templates/projects/js/annotation_guidelines_button.js
Disable the task submit buttons and show a UI message upon task timeout.
Re: https://github.com/bloomberg/pybossa/pull/664
=> RDISCROWD-4775 Disable submit buttons and show message upon task timeout.

templates/projects/tasks_browse.webpack.ejs
Backend ticket:
https://github.com/bloomberg/pybossa/pull/671
=> RDISCROWD-4597 Enable Ability to Sort Customized Columns in the Task List UI

.github/workflows/nodejs.yml, templates/projects/tasks_browse.webpack.ejs
related [PR](https://github.com/bloomberg/pybossa/pull/682).
=> change task browse/list page auto refrehing time to 3 min

templates/projects/tasks_browse.webpack.ejs
=> disable auto refresh

static/js/task-presenter-tabs.js, static/src/webpack.config.js, templates/projects/task_presenter_editor.html
- When saving on either the guidelines or task presenter tabs, both tabs contents (if modified) will save.
```
Test Suites: 30 passed, 30 total
Tests:       186 passed, 186 total
Snapshots:   0 total
Time:        120.929s
Ran all test suites.
```
=> RDISCROWD-4958 Save guidelines and task presenter tabs together.

templates/help/_tos.html
- Updated terms of service for clarity.
=> RDISCROWD-5131 Updated TOS

templates/projects/tasks_browse.webpack.ejs
=> grey out unavailable tasks

templates/projects/transferownership.html
- Update transferownership.html message.
Re: https://github.com/bloomberg/pybossa/pull/726
=> RDISCROWD-5093 Update transferownership.html message

static/css/projects.css, templates/projects/_helpers.html, templates/projects/base.html
- Fixed alignment of task list/browse button.
=> RDISCROWD-4886 Task List/Browse button alignment

templates/projects/task_scheduler.html
=> RDISCROWD-4703: Add reserve task category col. Refactor select2 code

templates/projects/js/annotation_guidelines_button.js, templates/projects/js/task_timeout.js, templates/projects/presenter.html
- Bug fix for task timeout warning in partial refresh.
- Store task Id, interval Id, original seconds, remaining seconds.
- Compares new task to old task to identify when to reset timer during partial refresh.
=> RDISCROWD-5142 Fix for task timeout warning

.github/workflows/nodejs.yml
Clear the cache to resolve the issue of "tarball data for resolve@1.1.7 (sha1-IDEU2CrSxe2ejgQRs5ModeiJ6Xs=) seems to be corrupted"
In Github
=> Fix npm cache issue

templates/projects/tasks_browse.webpack.ejs
=> RDISCROWD-5242: Enable task updates for regular coowner

static/sass/custom/dropdown.scss, static/src/components/setting/ownership_setting.vue, static/src/test/components/setting/ownship_setting.spec.js
- Added ability to add/remove email contacts for a project.
Re: https://github.com/bloomberg/pybossa/pull/761
=> RDISCROWD-4848 Custom email contacts

static/src/components/setting/ownership_setting.vue, static/src/test/components/ComponentColumn.spec.js, static/src/test/components/setting/ownship_setting.spec.js
- Added parameter to allow searching contacts against coowners.
- Fixed unit tests json payload for searching.
- Added unit tests for testing invalid search alert notification.
```
Test Suites: 32 passed, 32 total
Tests:       203 passed, 203 total
Snapshots:   0 total
Time:        9.649s
Ran all test suites.
```
Re: https://github.com/bloomberg/pybossa/pull/776
=> RDISCROWD-5412 - Search contacts with coowners and alert notification

static/js/tasks_browse.js
*Issue number of the reported bug or feature request: RDISCROWD-4878*
- When clicking bulk update dropdown button or bulk delete button, reset local selectedTask variable as well as the state.
related pr: https://github.com/bloomberg/pybossa/pull/777
=> RDISCROWD-4878 ask browse bulk edit state not updating

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js
*Issue number of the reported bug or feature request: RDISCROWD-5432*
Add a dropdown UI for configuring auto deleted completed tasks days.
local
Screenshot as below:
=> RDISCROWD-5432 Auto delete completed tasks after n days: UI changes

templates/projects/tasks_browse.webpack.ejs
=> RDISCROWD-5531 Disable sort.

templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs
=> RDISCROWD-4871: Update task browse ui for assigned users column

templates/projects/js/annotation_guidelines_button.js
**Issue number:** [RDISCROWD-5608](https://jira.prod.bloomberg.com/browse/RDISCROWD-5608)
Make task guidelines instructions sticky across tabs of the same project.
=> RDISCROWD-5608 Keep guidelines hidden

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js, templates/projects/update.html
=> RDISCROWD-5626: Add edit submission configuration

templates/projects/_helpers.html, templates/projects/task_scheduler.html, templates/projects/tasks.html, templates/projects/tasks_browse.webpack.ejs
=> RDISCROWD-5651: Enable browse task for regular user

templates/projects/task_scheduler.html
Enable customized columns for default task scheduler.
=> RDISCROWD-5651: Show customized columns for default scheduler

templates/_navbar.html
- Added logo banner background color to differentiate platforms.
```
SERVER_TYPE = 'Public QA'
DISPLAY_PLATFORM_IDENTIFIER = True
NAVBAR_COLOR = 'linear-gradient(44deg, #ff4326, #af3b06)'
```
Re: https://github.com/bloomberg/pybossa/pull/815
=> RDISCROWD-5652 Logo banner colors per platform

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js, templates/projects/update.html
=> RDISCROWD-5627: hide edit submission for priv

static/js/flashmessages.js
*Issue number of the reported bug or feature request: RDISCROWD-5717*
Implement the sticky functionality by checking where the user scrolls in the page 
Tested locally
Related PRs:
https://github.com/bloomberg/pybossa/pull/820
https://github.com/bloomberg/pybossa.js/pull/23
Screenshot as follows:
=> RDISCROWD-5717 change banner position for save and assign

static/js/tasks_browse.js, templates/account/profile.html, templates/admin/new_announcement.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/summary.html, templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs, templates/projects/wizard.html
Files to review
static/js/tasks_browse.js
templates/projects/tasks_browse.webpack.ejs
Rest of the files included in PR so that they're latest as per .ejs and are not required to be rebuild locally when respective .ejs not modified.
=> RDISCROWD-5703: Allow edit submission for admins, subadmins

templates/account/profile.html, templates/admin/new_announcement.html, templates/projects/_helpers.html, templates/projects/answerfieldsconfig.html, templates/projects/component_helper.html, templates/projects/new_blogpost.html, templates/projects/performancestats.html, templates/projects/summary.html, templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs, templates/projects/wizard.html
code changes to review
templates/projects/_helpers.html
templates/projects/tasks_browse.webpack.ejs
other changes are autogen and can be ignored for review
=> RDISCROWD-5699: Edit submission under task queue

static/js/tasks_browse.js
=> RDISCROWD-5784: Filters with edit submissions

static/js/flashmessages.js, static/js/tasks_browse.js, static/sass/pybossa/_flashmessages.scss, templates/projects/_helpers.html, templates/projects/tasks_browse.webpack.ejs
*Issue number of the reported bug or feature request: RDISCROWD-5630 & RDISCROWD-5790*
- Enhanced "pybossaNotify" function to support automatically disappearing, multiple sticky banners
- Show a switch button when there is saved task for the user
- Show a column in the task list page to indicate which task is saved. Make the column sortable and filterable.
Tested locally
Related PRs:
- https://github.com/bloomberg/pybossa.js/pull/25
- https://github.com/bloomberg/pybossa/pull/833
=> Rdiscrowd 5630 retrieve saved task UI

templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs
Update save taskbrowse bookmark icon to a floppy disk instead of cloud.
=> update taskbrowse bookmark icon

static/sass/custom/project.scss, static/sass/pybossa/_buttons.scss, templates/projects/_helpers.html
- Fix alignment for browse tasks button.
=> RDISCROWD-6204 Fix alignment for browse tasks button

static/sass/custom/project.scss, static/sass/pybossa/_buttons.scss, templates/projects/_helpers.html
- Adjusted css alignment on thanks for contributing button.
=> RDISCROWD-6204 Contribute button alignment

static/src/components/builder/components/TaskPresenter/TaskPresenterForm.vue, static/src/components/builder/store/modules/taskPresenter.js
*Issue number of the reported bug or feature request: RDISCROWD-5709*
* Responding to request for changes on this review ticket: RDISCROWD-5956
* Default the auto save seconds to 60 seconds
* Highlight the input field when the option is selected
* Remove extraneous imports
* Fix css selector
=> RDISCROWD-5709 Task Presenter Helper Component Auto Save Seconds

static/src/components/builder/components/AssistantLLM/AssistantLLMForm.vue
*Issue number of the reported bug or feature request: RDISCROWD-6091*
Added the notification "Please submit SDSK ADD 38813 for production use of LLMs" to the code builder.
=> RDISCROWD-6091: Add SDSK message to Assistant LLM code builder

templates/projects/publish.html
*Issue number of the reported bug or feature request: #RDISCROWD-6406*
=> RDISCROWD-6406 Add reminder to GIGwork to submit ticket for reporting

static/src/components/builder/components/AssistantLLM/AssistantLLMForm.vue
*Issue number of the reported bug or feature request: RDISCROWD-6709*
update LLM endpoint call arguments to match new API requirements.
- remove `num_beams`
- remove `logprobs`
=> RDISCROWD-6709 update llm endpoint

static/src/package-lock.json, static/src/package.json, static/src/yarn.lock
*Issue number of the reported bug or feature request: [RDISCROWD-6709](https://jira.prod.bloomberg.com/browse/RDISCROWD-6709)*
Bump task presenter components version
=> RDISCROWD-6709 update llm calls - task presenter components

static/src/package-lock.json, static/src/yarn.lock
RDISCROWD-6793 - update lock files
=> RDISCROWD-6793 - update lock files

templates/admin/usage_dashboard.html
=> RDISCROWD-7089 usage dashboard

static/src/components/fieldsconfig/redundancy_config.vue
*Issue number of the reported bug or feature request: [RDISCROWD-6334](https://jira.prod.bloomberg.com/browse/RDISCROWD-6334)*
- bugfix when updating answer field config
=> consensus ui bugfix

templates/account/js/metadata.js
*Issue number of the reported bug or feature request: DRQS 175516275*
Get reference to locations node from html selector instead of finding by id
- fixes bug where vendors don't see 'Languages' dropdown
Tested locally
=> use locations by id

static/src/components/builder/components/AssistantLLM/AssistantLLMForm.vue
*Issue number of the reported bug or feature request: [RDISCROWD-7467](https://jira.prod.bloomberg.com/browse/RDISCROWD-7467)*
Updated default parameters in code builder to align with OpenAI parameters as specified [here](https://bbgithub.dev.bloomberg.com/pages/ailm/llm-server/#/openai_migration?id=request-parameters).
=> RDISCROWD-7467: Update Code Builder with new Default Params

templates/projects/non_stats.html, templates/projects/stats.html
*Issue number of the reported bug or feature request: [RDISCROWD-7532](https://jira.prod.bloomberg.com/browse/RDISCROWD-7532)*
- add a link to grafana POC dashboard from GIGwork project stats page
Tested locally
=> Rdiscrowd 7532 grafana dash link

static/js/tasks_browse.js, templates/projects/tasks_browse.webpack.ejs
- Added ability to filter by assigned users in the browse tasks.
Re: https://github.com/bloomberg/pybossa/pull/951
=> RDISCROWD-7286 Filter by assigned user

static/src/components/setting/task_setting.vue, static/src/test/components/setting/task_setting.spec.js
=> RDISCROWD-7602: Reset presented UI

templates/projects/assign_users.html
- Added feature to sort users by last name.
- Added tooltip with email address.
- Hide disabled users.
Re: https://github.com/bloomberg/pybossa/pull/968
=> RDISCROWD-7561 Assign Users UI Enhancements

templates/projects/assign_users.html
- Update tooltip on keyup and paste (when searching).
Re: https://github.com/bloomberg/pybossa/pull/969
=> RDISCROWD-7561 Sorting users

static/src/components/setting/index.vue
- Sort users in alphabetical order by last name.
- Hide disabled users.
- Show email address in tooltip.
=> RDISCROWD-7671 Enhance assign users UI

static/src/components/setting/index.vue, static/src/components/setting/ownership_setting.vue, static/src/test/components/setting/index.spec.js, static/src/test/components/setting/ownship_setting.spec.js
*Issue number of the reported bug or feature request: [RDISCROWD-7088](https://jira.prod.bloomberg.com/browse/RDISCROWD-7088)*
Add ownership id field to project ownership page
Tested Locally
=> RDISCROWD-7088 add ownership id

static/src/components/setting/index.vue
*Issue number of the reported bug or feature request: #[RDISCROWD-7660](https://jira.prod.bloomberg.com/browse/RDISCROWD-7660)*
=> RDISCROWD-7660 - Add multi-select field option

templates/admin/usage_dashboard.html
- Added `Last Submission Date` and `Published` to the usage dashboard.
- Sort list of projects using each component by Last Submission date descending.
Re: https://github.com/bloomberg/pybossa/pull/995
=> RDISCROWD-7794 Component Usage Dashboard updates

templates/admin/usage_dashboard.html
- Added horizontal scroll.
- Adjusted min width of modal dialog.
=> RDISCROWD-7794 Scroll and min-width

static/src/components/builder/components/AssistantLLM/AssistantLLMForm.vue, static/src/components/builder/store/modules/assistantLLM.js
*Issue number of the reported bug or feature request: #RDISCROWD-7778*
=> RDISCROWD-7778 update LLM

static/src/components/setting/index.vue
*Issue number of the reported bug or feature request: RDISCROWD-791*
=> RDISCROWD-7917 - support improved flash message for error

templates/projects/update.html
*Issue number of the reported bug or feature request: RDISCROWD-7779*
=> RDISCROWD-7779 project dup task setting

templates/_formhelpers.html
*Issue number of the reported bug or feature request: RDISCROWD-7779*
=> RDISCROWD-7779 - dup task form helper update
