bloomberg/pybossa-default-theme

templates/account/public_profile.html
I removed the `current_user.is_authenticated` since it was wrong to call it as a property get, and it wasn't needed anyway.
=> RDISCROWD-1407 Allow users to edit their own metadata when enforce_privacy is on.

static/src/components/fieldsconfig/consensus_config.vue, static/src/components/fieldsconfig/field_config_base.vue, static/src/components/fieldsconfig/index.vue, static/src/components/fieldsconfig/store.js, static/src/test/components/fieldsconfig/consensus_config.spec.js, static/src/test/components/fieldsconfig/index.spec.js, static/src/test/components/fieldsconfig/store.spec.js, templates/projects/answerfieldsconfig.html, templates/projects/answerfieldsconfig.webpack.ejs
Changes: 
- shows consensus-config only if at least one answer field opt in "Retry".
- disable the "Save" button of answer fields config when at least one answer field opt in "Retry" but consensus-config is empty
- Add instruction tooltip on "answer field path" input box and "Retry" check box
Please review, thanks.
=> change UI to hide consensus-config when retry is not checked

static/css/task_browse.css, static/js/tasks_browse.js, templates/projects/tasks_browse.webpack.ejs
- Disabled the buttons **Make Gold** and **Update** for non-project owners and non-admins.
- Only project owners, sub-admin co-owners, and administrators may update a Gold task for a project.
This screenshot shows what the project owner sees when browsing tasks. The project owner (or an administrator) may create and/or update gold tasks.
This screenshot shows what a sub-administrator will see when browsing tasks. A sub-admin who is not the project owner may not make nor update gold tasks.
*Note: To create a project, a user must be either an admin or sub-admin. The project owner and co-owners will be included in project.owners_ids. If a co-owner is not a sub-admin, they will only have read access to gold tasks.*
Referencing https://github.com/bloomberg/pybossa/pull/252
=> RDISCROWD-1635: Disable updating a Gold task for non-owners of a project

static/src/components/builder/components/PreviewCommons.vue
The component builder is not validating some of the components correctly which is preventing the code generation and preview for them. This is due to a change we made to validation to return an object instead of a boolean, and we forgot to update some of the component builders.
=> Validate correctly in component builder.

templates/projects/task_presenter_editor.html
=> RDISCROWD-1694 Style fix for css word-break

static/src/components/builder/components/CheckboxInput/CheckboxInputForm.vue, static/src/components/builder/components/RadioInput/RadioInputForm.vue, static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/components/TextInput/TextInputForm.vue, static/src/components/builder/components/TextTagging/TextTaggingForm.vue
*Issue number of the reported bug or feature request: #RDISCROWD-1828*
Made NLP Enrichment component builder tag name field into a dropdown instead of text box.
Added standard label tip for "Answer field name" on all component builders.
Corrected dropdown appearance.
Fixed some label->control associations. 
Removed zoom on hover for label tip.
Changed wording from "Add Tag" to "New Tag" on add tag button.
Manual
=> Add dropdown for tag name.

static/src/components/builder/components/RadioInput/RadioCreator.vue, static/src/components/builder/components/RadioInput/radioInputTemplate.html, static/src/components/builder/utils.js, static/src/package.json, static/src/test/utils.spec.js
*Issue number of the reported bug or feature request: #RDISCROWD-1868*
We changed the way initial values are specified for RadioInput components. So we have to update the component builder to use the new way.
Manual
=> Update RadioInput builder for v0.3.4.

static/src/components/builder/components/TextTagging/TextTaggingForm.vue, static/src/components/builder/store/modules/textTagging.js
*Issue number of the reported bug or feature request: #RDISCROWD-1877*
When the entities variable binding is not specified in the NLP Enrichment component builder, the generated code is invalid.
Manual
=> Fix invalid generated NLP Enrichment component.

templates/projects/quiz_mode.html
*Issue number of the reported bug or feature request: #RDISCROWD-1892*
In the quiz result table we need to show whether the quiz is enabled for a user. Not showing this information can lead to a project owner not being able to diagnose why a user is not entering quiz mode.
Manual
=> Show quiz enabled state in quiz table.

templates/projects/tasks_browse.html
*Issue number of the reported bug or feature request: #RDISCROWD-1476*
We do not want worker co-owners to be able to tell which tasks are gold tasks. So in the task browse screen we need to hide any information that would give that away. Hiding the task redundancy, % complete, and Gold columns does that, along with removing gold_answers from results.json.
We probably still need to modify the downloaded reports to hide the gold info.
Manual testing with a worker co-owner account I created.
=> Hide gold task info for worker co-owners.

templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs
*Issue number of the reported bug or feature request: #RDISCROWD-1957*
These changes were made in the wrong file before. In addition to those changes, we are hiding the color indicator on the task id that tells whether the task is gold or completed or normal.
Manual
=> Hide all gold info from worker co-owners.

templates/projects/settings.html, templates/projects/tasks.html
- Fixed duplicate ID property for "manage_coowners".
- Removed duplicate "Export Project Report" from Tasks page.
- Facilitates automation and proper HTML structure.
=> RDISCROWD-1921 Added unique ID for "export_project" and "manage_coowners".

templates/projects/task_presenter_editor.html
- Collapse github and sync panels by default if no information is present.
- Added icon styling to panels.
=> RDISCROWD-1867 Github and Sync Panel Collapse and Styling

templates/projects/presenter.html
Fix guidelines display when it has special characters like '
=> Fix guidelines display

templates/projects/settings.html, templates/projects/update.html
Two options `delete project` and `data enrichment` had mismatching ids which conflicted with other ids on the page.
The password field had both a div and an input with the same id, so I removed the div.
```
<div id="password"><div class="form-group ">
<label for="password" class="control-label"><label for="password">Password</label></label>
<input class="form-control" id="password" name="password" placeholder="Leave blank to maintain set password" type="text" value="">
</div></div>
```
=> Fixed issues with duplicated ids

templates/projects/annotations.html
*Issue number of the reported bug or feature request: #<RDISCROWD-2687 & 2685>
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2687
https://jira4.prod.bloomberg.com/browse/RDISCROWD-2685
- remove Label Aggregation Strategy dropdown from annotation setting page;
- remove Input Schema input box  from annotation setting page; 
- remove Output Schema input box  from annotation setting page;
=> UI change correspond to ampDisco schema change

static/sass/custom/taskpresenter.scss
- Adjusted font color for non-active tabs to not appear disabled.
Inactive tabs currently appear disabled, in font color. This PR darkens the font.
Should we make the active tab font color black and non-active tabs blue to follow Bootstrap's [default](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior) tab color?
=> Adjusted active tab font color.

static/src/components/builder/components/Table/checkboxInputColumnTemplate.html, static/src/components/builder/components/Table/textInputColumnTemplate.html, static/src/components/builder/utils.js, static/src/test/utils.spec.js
*Issue number of the reported bug or feature request: #<2942>*
https://jira.prod.bloomberg.com/browse/RDISCROWD-2942
Add `:initial-value` attribute to table components
=> Fix table component bug - add initial values

static/src/components/builder/components/Table/TableForm.vue, static/src/components/builder/store/modules/table.js
We say `column_id` is optional , with a default value '__col_id', but we do not have default value here.
=> fix typo and default column_id

templates/_flash_messages.html
- Added fix for Markdown formatting of announcement messages.
*This fix applies the same Markdown formatting as that used in the [announcement.html](https://github.com/bloomberg/pybossa-default-theme/blob/master/templates/admin/announcement.html#L27) template on the Admin screen.*
=> Fix for announcements not rendering Markdown format.

templates/projects/update.html
*Issue number of the reported bug or feature request: RDISCROWD-2967*
I removed line line  55, {{ render_field(form.webhook) }}, from update.html to hide the webhook entry field which is not currently being used.
=> RDISCROWD-2967: Remove webhook field from update form

templates/projects/js/amp_store.js, templates/projects/new.html, templates/projects/update.html
https://jira.prod.bloomberg.com/browse/RDISCROWD-3031
- add js code to /update and /new page so that if the user chooses L1 for either input_data_class or output_data_class, uncheck opt-in checkbox
Re: https://github.com/bloomberg/pybossa/pull/481
=> RDISCROWD-3031 - default optout L1 projects

templates/projects/new.html, templates/projects/update.html
https://jira.prod.bloomberg.com/browse/RDISCROWD-3134
The ProjectCommonForm and ProjectUpdateForm passwords were both TextFields instead of Password fields. I changed this and also added type="password" to the render_field in the html for projects/new.html and projects/update.html. 
I checked to see that these fields were rendering correctly locally.
***Screenshot***
=> RDISCROWD-3134: Hide Password in Project Settings Password Field 

templates/admin/index.html
https://jira.prod.bloomberg.com/browse/RDISCROWD-3162
- removed news block from admin/index.html
Loaded the changed page locally and saw that the text was now removed. 
Before: 
After:
=> RDISCROWD-3162: removing news block from admin/index.html

templates/account/email/adminbssonotification.html, templates/account/email/adminbssonotification.md
https://jira.prod.bloomberg.com/browse/RDISCROWD-3216
Tim requested that an email be sent to his account when an account is created via the BSSO route, as well as to display a flash message to the user indicating that a new account has been created for them using BSSO. This required adding the conditional to send the message, the message creation function, the message html/md, and the related test.
I added a new test and also tested locally.
=> RDISCROWD-3216: BSSO account creation alert

templates/projects/external_config.html
*Issue number of the reported bug or feature request: RDISCROWD-3304*
I added the warning text to the external configuration UI. 
I checked in the UI locally and it looks good.
Usage
Edit settings_local.py and set a value as shown below.
EXT_CONFIG_DOCS = [Link to External Configuration Documentation]
Screenshots available in JIRA ticket: 
https://jira.prod.bloomberg.com/browse/RDISCROWD-3304
=> add warning to external config

templates/projects/project.html
*Issue number of the reported bug or feature request: RDISCROWD-3501*
Add another row in the table to display "Number of priority 1 tasks in queue"
Tested locally
**Related PR**
https://github.com/bloomberg/pybossa/pull/526
=> RDISCROWD-3501 Create Number of Priority 1 Tasks Info Field

.travis.yml, static/src/package.json
Issue number of the reported bug or feature request: RDISCROWD-3556
Describe your changes
Replacing Bintray npm repo URL with AWS S3. It first grabs the @dtwebservices/task-presenter-components version from [package.json](https://github.com/bloomberg/pybossa-default-theme/blob/ab51a7639da52ac08b11a545acd7640ecfe3e900/static/src/package.json#L15) file. Then it executes npm install <tarball-url> command, which will install task-presenter-components as well as update its version in the package.json file with the aws s3 url.
Testing performed
Test locally
Related [PR](https://bbgithub.dev.bloomberg.com/GIGwork/pybossa-vue/pull/103)
=> RDISCROWD-3556 replace Bintray with AWS

templates/projects/external_config.html
- Moved external configuration help to settings_local.py under `EXT_CONFIG_TIPS`.
- Defined additional help for external configuration settings for buckets.
```python
EXT_CONFIG_TIPS = [
'The bucket you plan to access already exists (GIGwork will not create this for you).',
'You have spelled the bucket name correctly.',
'You have permission to access the bucket you plan to use.',
'You have granted read/write access on your bucket to _____.'
]
```
`EXT_CONFIG_TIPS` is an array of strings to render.
If `EXT_CONFIG_TIPS` is not defined, the tips are omitted.
_____
*The External Configurations page tends to be a problematic area with higher user mistakes. Adding detailed help items may reduce user error.*
=> Additional help added to external configuration page.

templates/projects/publish.html
*Issue number of the reported bug or feature request: #RDISCROWD-1478*
After clicking the Unpublish Project button, a warning modal appears and a second click to confirm they really want to unpublish.
tested locally 
=> RDISCROWD-1478 Secondary Confirmation When Unpublishing a Project

static/css/task_browse.css, static/js/nav.js, static/sass/custom/project.scss, templates/_navbar.html, templates/projects/_helpers.html, templates/projects/base.html, templates/projects/tasks_browse.html
- Left-nav icons.
- Left-nav collapse bar.
- Left-nav alignment.
- Task browse table filters bar alignment.
- Added "Displaying tasks 1-10 of 20" for pagination.
- Task browse table column width adjustment.
- Expanded page width when left-nav is collapsed.
- Task browse table hover effect on rows.
- Task browse table striped rows.
- Persistence for left-nav collapse state via cookie, supports smooth client and server-side rendering upon page load.
=> RDISCROWD-4451 Collapsible left-nav and responsive browse tasks table

templates/projects/base.html, templates/projects/tasks_browse.html, templates/projects/tasks_browse.webpack.ejs
- Fixed paging max limit on the task browse page.
`Displaying tasks 1-4 of 4`
instead of
`Displaying tasks 1-20 of 4.`
=> Task browse paging limit.

templates/projects/_helpers.html, templates/projects/tasks_browse.webpack.ejs
- Allow toggle between browse tasks and task list views.
- Task list view for admins/owners displays the same view as a worker would see (including hidden instructions panel and limited buttons _[Filters, page, search]_)
Re: https://github.com/bloomberg/pybossa/pull/638
=> RDISCROWD-4747 Allow toggle between browse tasks and task list views.

static/src/package.json
*Issue number of the reported bug or feature request: NULL*
Downgrade d3 build to use the exact version 3.5.15
Tested locally
The current approximate version ~3.5.17 uses 3.5.17, which causes import error for ```import * as d3 from 'd3'```
=> downgrade d3 to 3.5.15 to resolve import issue

templates/_ga.html
- Upgraded Google Analytics UA to [Google Analytics 4](https://support.google.com/analytics/answer/10759417).
```
{% if config.GA_ID %}
<script async src="https://www.googletagmanager.com/gtag/js?id={{config.GA_ID}}"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '{{config.GA_ID}}');
</script>
{% endif %}
```
```
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JEE40ZJ3VK"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-JEE40ZJ3VK');
</script>
```
```text
Request URL: https://www.googletagmanager.com/gtag/js?id=G-JEE40ZJ3VK
Request Method: GET
Status Code: 200 OK
Remote Address: …
```
=> RDISCROWD-1740 Google Analytics 4

static/css/task_browse.css, templates/projects/tasks_browse.webpack.ejs
- Added styling to browse tasks table.
- Added blue hover effect for column headers.
- Added column spacing.
- Added css class `border` for `#tasksGrid` table element to show/hide table cell borders.
=> RDISCROWD-5067 Style browse tasks table

templates/projects/task_scheduler.html
select2 auto sorts alphabetically the selected items thereby loosing track of the order of selection. There's no option provided by select2 that can disable autosort; [PR](https://github.com/select2/select2/pull/6014/files) on similar lines was closed in the past. Hence, solution was to implement jquery to trap selection event as described [here](https://stackoverflow.com/questions/31431197/select2-how-to-prevent-tags-sorting).
=> RDISCROWD-5073: disable select2 autosort for task list columns selection.

static/src/package.json
*Issue number of the reported bug or feature request: NULL*
When running "yarn webpack" in Jenkins, it appears the following error:
ERROR in ./node_modules/simplemde/src/js/simplemde.js
2022-06-08 17:16:40 |  Module not found: Error: Can't resolve 'codemirror/addon/display/fullscreen.js' in '/build/pybossa/pybossa/themes/default/static/src/node_modules/simplemde/src/js
Could be related to codemirror version. So the change is to use a specific version.
tested locally.
=> add codemirror 5.65.1

static/src/components/setting/task_setting.vue
- Bug fix retain customized_columns when saving.
- Correctly maintains customized_columns value while allowing user to clear value if explicitly chosen.
Re: https://github.com/bloomberg/pybossa/pull/743 *(<-- this PR may be closed without merge)*
=> RDISCROWD-5267 Bug fix retain customized_columns when saving.

static/css/task_browse.css
- CSS fix for assign users dropdown menu.
**Hovering the mouse over the bottom-right corner of the menu no longer activates the underlying slider control.**
**Hovering the mouse over the bottom-right corner of the menu accidentally activates the underlying slider control.**
=> RDISCROWD-5407 Assign users dropdown menu

templates/projects/project.html
- Allow all users to view project info fields: Number of tasks in queue, Number of priority 1 tasks in queue, Number of tasks in progress
=> RDISCROWD-5481 Addition project info fields for workers

static/css/projects.css, templates/projects/project.html
- Disable image upload from task guidelines widget (keep ability to link images).
- Cleanup UI borders for modals.
Note, button for "Upload" is no longer displayed. Border spacing has been cleaned up.
Note, button for uploading files. Incorrect border spacing.
=> RDISCROWD-5307 Disable image uploads in task guidelines

static/js/nav.js, templates/base.html
*Issue number of the reported bug or feature request: [RDISCROWD-5609](https://jira.prod.bloomberg.com/browse/RDISCROWD-5609)
Previously: When the user finishes all tasks, they are left hanging looking at their last completed task. It's extra work for them to manually get to the project home page.
Now: When the user finishes all tasks, they are automatically redirected to the project home page.
Tested locally
**Additional PR**
https://github.com/bloomberg/pybossa.js/pull/17
=> RDISCROWD-5609 Redirect to project home on task completion

templates/projects/task_presenter_editor.html
*Issue number of the reported bug or feature request: [RDISCROWD-5716](https://jira.prod.bloomberg.com/browse/RDISCROWD-5716)*
- add button to expand TP code.
- Tooltip on button to show how to shrink TP code back to normal size.
Tested locally
=> RDISCROWD-5716 add expand btn

static/src/components/builder/components/TaskPresenter/TaskPresenterForm.vue, static/src/components/builder/store/modules/taskPresenter.js
*Issue number of the reported bug or feature request: RDISCROWD-5709*
In the Task Presenter component, `:auto-save-seconds` should reset to 0 when partial saving is disabled.
=> RDISCROWD-5709 - Autosave duration default

templates/projects/_helpers.html, templates/projects/base.html
*Issue number of the reported bug or feature request: #RDISCROWD-6222*
Show GIGwork users why no tasks are available
Because of null checks, template will not crash if variables are not present.
=> RDISCROWD-6222 Show GIGwork users why no tasks are available

static/src/components/builder/components/Questions.vue
- Renamed helper component "NLP Enrichment" to "Span Annotation (NER)".
=> RDISCROWD-5830 Rename NLP Enrichment to Span Annotation (NER)

static/src/components/builder/components/Anco/AncoTemplate.html, static/src/components/builder/utils.js, static/src/package-lock.json, static/src/package.json, static/src/yarn.lock
*Issue number of the reported bug or feature request: RDISCROWD-6793*
A bug was discovered wherein if the `:annotation-url` prop was present but empty (`:annotation-url=''`), it would cause the `<anco>` helper component to crash upon loading. This change removes the prop if it is empty.
Tested locally, screenshots attached.
**1. When `:annotation-url` is NOT set:**
**2. When `:annotation-url` is set:**
=> RDISCROWD-6793 (4) hide empty helper component prop when empty

static/src/components/setting/index.vue
*Issue number of the reported bug or feature request: RDISCROWD-6970*
Add support for a placeholder attribute. `Wizard > Settings` does not currently have field labels for every input, and this can be confusing when there are multiple input fields.
**Testing performed (screenshot)**
=> RDISCROWD-6970 add support for placeholder attr

templates/admin/usage_dashboard.html
- Updated admin project stats usage dashboard to include project_ids and project_names, along with counts.
Re: https://github.com/bloomberg/pybossa/pull/903
=> RDISCROWD-7089 Usage stats to include project ids and project names

static/src/answerfieldsconfig.js, static/src/components/fieldsconfig/index.vue, static/src/components/fieldsconfig/redundancy_config.vue, static/src/components/fieldsconfig/store.js, static/src/components/setting/consensusMethods.js, static/src/components/setting/consensus_setting.vue, static/src/setting.js, static/src/test/components/fieldsconfig/redundancy_config.spec.js, static/src/test/components/setting/consensus_setting.spec.js, templates/projects/answerfieldsconfig.html, templates/projects/answerfieldsconfig.webpack.ejs, templates/projects/summary.html, templates/projects/summary.webpack.ejs
*Issue number of the reported bug or feature request: RDISCROWD-6334*
- refactor existing `ConsensusConfig` component to `RedundancyConfig`
- add new `ConsensusConfig` component
- responsive settings based on which consensus method is chosen
- Add new tab 'Consensus' for task level consensus settings
- Add UI headers in 'project settings -> Answer' for Answer field config and Redundancy Config
- Consensus Method: how to calculate consensus
- options: F1, Jaccard, Dice, Overlap, Majority
- Agreement threshold: what percentage of the two answers must match for agreement (pairwise comparison)
- Consensus threshold: what total percentage of answers need to match for there to be consensus or not
- Determines if redundancy will be updated
example project:
```
{
"id": 1,
"created": …
```
=> Rdiscrowd 6334 v2

templates/projects/answerfieldsconfig.html, templates/projects/answerfieldsconfig.webpack.ejs
- fix bug where `project/[project_shortname]/answerfieldsconfig` does not load form
**Additional Context:**
https://github.com/bloomberg/pybossa-default-theme/pull/454
answer consensus configuration was previously split into 2 elements, `consensus-config` and `redundancy-config`. Backend still represents them as one object, `consensus_config`. To be cleaned once we build out backend
JIRA for future cleanup: https://jira.prod.bloomberg.com/browse/RDISCROWD-7377
=> answerfieldsconfig Bugfix

static/src/components/builder/components/AssistantLLM/AssistantLLMForm.vue, static/src/components/builder/store/modules/assistantLLM.js
*Issue number of the reported bug or feature request: [RDISCROWD-7366](https://jira.prod.bloomberg.com/browse/RDISCROWD-7366)*
Switched flan for mixtral so code builder uses correct model.
Tested locally with sample project.
=> RDISCROWD-7366 Update GIGwork Private QA to use the Mixtral LLM model

templates/projects/settings.html, templates/projects/update.html
*Issue number of the reported bug or feature request: [RDISCROWD-7338](https://jira.prod.bloomberg.com/browse/RDISCROWD-7338)*
- enable assigning users to projects
- remove project password button in project settings
**Remove Project Password Button:**
**UPDATED BUTTON:**
**Confirmation alert:**
=> RDISCROWD-7338 project password --> assign user to project

static/src/components/setting/ownership_setting.vue, static/src/test/components/setting/ownship_setting.spec.js, templates/projects/summary.webpack.ejs
*Issue number of the reported bug or feature request: [RDISCROWD-7088](https://jira.prod.bloomberg.com/browse/RDISCROWD-7088)*
- v2 of https://github.com/bloomberg/pybossa-default-theme/pull/469
- switch to `/api/project/<short_name>`
=> RDISCROWD-7088 Ownership ID v2

static/src/components/setting/index.vue, static/src/test/components/setting/index.spec.js, templates/projects/external_config.html
*Issue number of the reported bug or feature request: #RDISCROWD-7660*
=> RDISCROWD-7660-2 show authorized servcies to non-admins

templates/projects/external_config.html
*Issue number of the reported bug or feature request: #RDISCROWD-7660*
=> RDISCROWD-7660 move authorized services section

templates/423.html
*Issue number of the reported bug or feature request: [RDISCROWD-7741](https://jira.prod.bloomberg.com/browse/RDISCROWD-7741)
Add 423 locked template for when users are unauthorized to access a project.
=> RDISCROWD-7741 add 423 template

templates/account/user_pref_metadata.html
*Issue number of the reported bug or feature request: [RDISCROWD-7362](https://jira.prod.bloomberg.com/browse/RDISCROWD-7362)*
Add parenthesis around country codes for easy identification
=> RDISCROWD-7362 update location pref UI

templates/423.html
*Issue number of the reported bug or feature request: [RDISCROWD-7852](https://jira.prod.bloomberg.com/browse/RDISCROWD-7852)*
Add project owner name to 423 error page
https://github.com/bloomberg/pybossa/pull/1012
=> RDISCROWD-7852 - add Project owner name to 423 error page

templates/_formhelpers.html
*Issue number of the reported bug or feature request: #RDISCROWD-7779*
Fixes this error in tests:
```
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/json/encoder.py line 257 in iterencode
return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not Undefined
```
=> RDISCROWD-7779-3 fix form helper key error
